apiVersion: v1
kind: Service
metadata:
  name: flask-file-upload-service
spec:
  selector:
    app: flask-file-upload
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5500
  type: LoadBalancer
